### ISSUE TITLE
CSS mucks with table style for any other table

### ISSUE THREAD

**Issue by finger563** [dfst/webgme-fab#4]
When FAB is being used, it sets styles for the table class that control any other table's styles:

![image](https://cloud.githubusercontent.com/assets/213467/14427498/b6859028-ffba-11e5-984c-1e60feab5777.png)

This should look like this:

![image](https://cloud.githubusercontent.com/assets/213467/14427638/505aae5e-ffbb-11e5-8f78-a0babc52fa73.png)

I think that if the style were altered in https://github.com/dfst/webgme-fab/blob/master/src/visualizers/panels/FloatingActionButton/styles/css/materialize-fab.css#L2242 then it might be fixed.

**Comment by brollb** [comment]
can you check out https://github.com/dfst/webgme-fab/pull/5 and verify that the fix works?
