### ISSUE TITLE
the floating button not visible

### ISSUE THREAD

**Issue by yogeshVU** [dfst/webgme-fab#48]
After cloning and running  as described in the readme, the floating point is not visible. I am sure I am missing something
```
git clone https://github.com/dfst/webgme-fab
cd webgme-fab
npm install
npm start
````

**Comment by brollb** [comment]
Yeah, it needs to be added to a layout. Basically, the webgme-fab is a visualizer (like ModelEditor, etc) but is a *secondary* visualizer so it doesn't show up in the dropdown. However, it still needs to be added to the layout somehow. Have you done much with layouts before?

Do you want to use the default webgme layout and just add the button or are you making other significant ui changes, too? If you are looking for a simplified layout, you can use the cfh-layout (only has a **c**enter, **h**eader, and **f**ooter) but if you are looking to just augment the current layout, I believe @finger563 has one that he uses with the webgme-fab

**Comment by yogeshVU** [comment]
I think just the default layout will be enough for me. So basically need to add the floating button to the layout. Sorry no experience with the layouts customization.

**Comment by yogeshVU** [comment]
Also does one need to call 
```
webgme import viz FloatingActionButton webgme-fab
```

**Comment by brollb** [comment]
Sorry for the delayed response. Yes, you want to run the manual import to make sure the webgme config can be updated by the webgme-cli automatically!
