### ISSUE TITLE
css styles conflict with headers and lists.

### ISSUE THREAD

**Issue by finger563** [dfst/webgme-fab#7]
From what I can tell you shouldn't need the `header` styles in your css (I didn't see a place where you actually used them, but I didn't look through _all_ your code :P ).

However, you should use your own class definitions or IDs for `list` styling as you do need that and it conflicts with anything else that might use default list classes.

**Comment by brollb** [comment]
yeah, I am going to have to go through the css and pull out the few things that I actually use to avoid these problems.

At a glance, it looks like these are the classes used:
- `tooltipped`
- `btn-floating`
- `btn-large`
- `disabled`
- `material-icons`
- `fixed-action-btn`
- any color classes

I should go through and remove any css not related to these classes. However, it also uses the toasts, so those classes should remain.

After removing all other rules, these still should be placed within a class `webgme-fab` so the rules are essentially namespaced

**Comment by brollb** [comment]
Can you check out branch [7-namespace-css](https://github.com/dfst/webgme-fab/tree/7-namespace-css)? It should fix the issue
